#!/bin/bash
#
# This script cleans up temporary files in the current directory and its subdirectories.
# Usage:
#   clean
#

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
RESET='\033[0m'

# Clean up temporary files
find -name "*~" -delete 
find -name "#*#" -delete 
find -name "*.swp" -delete 
find -name "*.swo" -delete 
find -name "*.gcda" -delete 
find -name "*.gcno" -delete 
find -name "*.log" -delete
find -name "*.o" -delete

echo -e "${GREEN}✅ Cleaned up temporary files${RESET}"
