#!/bin/bash

GREEN='\033[1;32m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
RESET='\033[0m'

DOCKER_SOCKET_PATH=/var/run/docker.sock
EXPORT_FILE="coding-style-reports.log"
IMAGE_LAST_PULL_FILE="/tmp/coding_style_checker_last_pull"

BANNED_EXTENSIONS=("md")

function show_usage() {
    echo ""
    echo "Usage: $(basename $0) DELIVERY_DIR REPORTS_DIR"
    echo -e "\tDELIVERY_DIR\tShould be the directory where your project files are"
    echo -e "\tREPORTS_DIR\tShould be the directory where we output the reports"
    echo -e "\t\t\tTake note that existing reports will be overriden"
    echo ""
}

display_results() {
    local last_file=""
    local sum=0
    while read -r line; do
        current_file=$(echo "$line" | cut -d ':' -f 1)

        file_extension="${current_file##*.}"
        if [[ " ${BANNED_EXTENSIONS[@]} " =~ " ${file_extension} " ]]; then
            continue
        fi

        error_type=$(echo "$line" | awk -F: '{print $3}' | cut -d '-' -f 1 | sed 's/^[[:space:]]*//')

        if [[ "$error_type" == "MINOR" ]]; then
            color="$YELLOW"
        elif [[ "$error_type" == "MAJOR" ]]; then
            color="$RED"
        elif [[ "$error_type" == "INFO" ]]; then
            color="$BLUE"
        fi

        current_file=$(echo "$current_file" | sed 's|^\./||')

        if [[ -f .gitignore ]]; then
            if grep -q "$current_file" .gitignore || grep -q "*.${current_file##*.}$" .gitignore; then
                # echo -e "🚫 ${RED}${current_file} is ignored due to $(grep "*.${current_file##*.}$" .gitignore) rule in .gitignore${RESET}"
                continue
            fi
        fi

        if [[ "$current_file" != "$last_file" ]]; then
            echo "------------------------------------------"
            last_file="$current_file"
        fi

        path_and_line=$(echo "$line" | cut -d ':' -f 1,2)
        path_and_line=$(echo "$path_and_line" | sed 's|^\./||')
        message=$(echo "$line" | cut -d ':' -f 3-)
        printf "%-30s ${color}${message}${RESET}\n" "$path_and_line"

        ((sum++))

    done < "$EXPORT_FILE"

    if (( sum == 0 )); then
        echo -e "✅ ${GREEN}No coding style issues found${RESET}"
    else
        echo "------------------------------------------"
    fi
    rm -f "$EXPORT_FILE"
}

should_pull_image() {
    if [[ "$FORCE_PULL" == "true" ]]; then
        return 0
    fi
    if [[ -f "$IMAGE_LAST_PULL_FILE" ]]; then
        last_pull_time=$(cat "$IMAGE_LAST_PULL_FILE")
        current_time=$(date +%s)
        time_diff=$((current_time - last_pull_time))
        if (( time_diff < 86400 )); then
            return 1
        fi
    fi
    return 0
}

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    show_usage
else
    DELIVERY_DIR=$(pwd)
    REPORTS_DIR=$(pwd)
    FORCE_PULL="false"
    HAS_SOCKET_ACCESS=$(test -r $DOCKER_SOCKET_PATH; echo "$?")
    BASE_EXEC_CMD="docker"

    for arg in "$@"; do
        case $arg in
            -f)
                FORCE_PULL="true"
                shift
                ;;
            *)
                ;;
        esac
    done

    rm -f "$EXPORT_FILE"

    if [ $HAS_SOCKET_ACCESS -ne 0 ]; then
        echo -e "${YELLOW}WARNING: Socket access is denied${RESET}"
        echo "To fix this we will add the current user to docker group with : sudo usermod -a -G docker $USER"
        read -p "Do you want to proceed? (yes/no) " yn
        case $yn in
            yes | Y | y | Yes | YES)
                echo "ok, we will proceed"
                sudo usermod -a -G docker $USER
                echo -e "${YELLOW}You must reboot your computer for the changes to take effect${RESET}";;
            no | N | n | No | NO)
                echo "ok, Skipping";;
            *)
                echo "invalid response, Skipping";;
        esac
        BASE_EXEC_CMD="sudo ${BASE_EXEC_CMD}"
    fi

    if should_pull_image; then
        echo -e "🔑 ${YELLOW}Fetching token...${RESET}"
        GHCR_REGISTRY_TOKEN=$(curl -s "https://ghcr.io/token?service=ghcr.io&scope=repository:epitech/coding-style-checker:pull" | grep -o '"token":"[^"]*' | grep -o '[^"]*$')
        GHCR_REPOSITORY_STATUS=$(curl -I -f -s -o /dev/null -H "Authorization: Bearer $GHCR_REGISTRY_TOKEN" "https://ghcr.io/v2/epitech/coding-style-checker/manifests/latest" && echo 0 || echo 1)
        if [ $GHCR_REPOSITORY_STATUS -eq 0 ]; then
            echo -e "🚚 ${PURPLE}Pulling latest coding style checker image...${RESET}"
            $BASE_EXEC_CMD pull ghcr.io/epitech/coding-style-checker:latest > /dev/null 2>&1 && $BASE_EXEC_CMD image prune -f > /dev/null 2>&1
            date +%s > "$IMAGE_LAST_PULL_FILE"
        else
            echo -e "${YELLOW}WARNING: Skipping image download${RESET}"
        fi
    else
        echo -e "🕒 ${PURPLE}Using cached coding style checker image...${RESET}"
    fi

    echo -e "🔍 ${BLUE}Checking coding style...${RESET}"
    $BASE_EXEC_CMD run --platform linux/amd64 --rm -i -v "$DELIVERY_DIR":"/mnt/delivery" -v "$REPORTS_DIR":"/mnt/reports" ghcr.io/epitech/coding-style-checker:latest "/mnt/delivery" "/mnt/reports"

    if [[ -f "$EXPORT_FILE" ]]; then
        display_results
    fi
fi
